services:
  backend:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    working_dir: /app
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      
    networks:
      - app_network
    environment:
      - PATH=/root/.dotnet/tools:$PATH
    depends_on:
      - db

  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    networks:
      - app_network

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: aissh_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:



